### ISSUE TITLE
Inconsistent handling of a username that is `None`

### ISSUE THREAD

**Issue by cobusc** [kencochrane/django-defender#110]
Calling `utils.record_failed_attempt(some_ip, None)` currently creates an entry with key `defender:failed:username:None` in Redis. The count is updated as expected for repeated calls.

The problem is that neither `utils.reset_failed_attempts` or `utils.unblock_username` can be used to clear the counts:
```
def unblock_username(username, pipe=None):
    """ unblock the given Username """
    do_commit = False
    if not pipe:
        pipe = REDIS_SERVER.pipeline()
        do_commit = True
    if username:
        pipe.delete(get_username_attempt_cache_key(username))
        pipe.delete(get_username_blocked_cache_key(username))
        if do_commit:
            pipe.execute()
```
The explicit check for `username` means that neither `delete` call gets made.

IMHO `username=None` should not result in a Redis entry being made. This means that the `utils.record_failed_attempt` function should be modified:
```python

    user_block = False
    if username and not config.DISABLE_USERNAME_LOCKOUT:
        user_count = increment_key(get_username_attempt_cache_key(username))
        # if over the limit, add to block
        if user_count > config.FAILURE_LIMIT:
            block_username(username)
            user_block = True
```
Note the more restrictive `if username and not config.DISABLE_USERNAME_LOCKOUT:` check.
The same would apply for IP addresses, but it is less likely to present itself since IP addresses are typically available in the request.

**Comment by kencochrane** [comment]
@cobusc thanks for the report, would you have time to submit a PR with the change you proposed?

**Comment by cobusc** [comment]
https://github.com/kencochrane/django-defender/pull/112

**Comment by cobusc** [comment]
Closed by https://github.com/kencochrane/django-defender/commit/5aa69bac96e0a82d773d1aa13a817862ccfc555f
