### ISSUE TITLE
Dispatch signal when blocking username and IPs

### ISSUE THREAD

**Issue by williamboman** [kencochrane/django-defender#111]
In my case, I'd like to send an email to users when their account is locked. It would be nice to be able to register a [signal](https://docs.djangoproject.com/en/2.0/topics/signals/) listener for when `django-defender` issues a username/IP block.

**Comment by kencochrane** [comment]
I think this is a duplicate of #41

**Comment by williamboman** [comment]
That is correct, my bad.
