### ISSUE TITLE
New pypi release to fix dependency issue with Django 1.11.x

### ISSUE THREAD

**Issue by livenson** [kencochrane/django-defender#116]
We are using Django 1.11.4, which should totally work, but the installation is failing due to a conflict:

```
error: Django 1.11.4 is installed but Django<=1.11,>=1.8 is required by set(['django-defender'])
```
Seems to be ok with master -- but we'd need something from pypi. Thanks!

**Comment by kencochrane** [comment]
0.5.2 is now on pypi : https://pypi.python.org/pypi/django-defender/0.5.2

**Comment by livenson** [comment]
Thanks! It would be great to get another release once https://github.com/kencochrane/django-defender/pull/115 is merged. We are packaging defender into RPMs and these extra dependencies are not making life easier at all.

**Comment by kencochrane** [comment]
@livenson yes, I was hoping to have everything in this release, but didn't want to keep everyone waiting, hopefully we can get the other PR's merged, and once we do, I'll do another release.

**Comment by livenson** [comment]
@kencochrane , any chance of doing a 0.5.3 release with dropped mock dependency?

**Comment by kencochrane** [comment]
0.5.3 is on PyPi https://pypi.python.org/pypi/django-defender/0.5.3
