### ISSUE TITLE
Use cache backend/framework instead of Redis?!

### ISSUE THREAD

**Issue by blueyed** [kencochrane/django-defender#117]
What is the reason behind not just using Django's cache framework?

With https://github.com/kencochrane/django-defender/issues/81 and https://github.com/kencochrane/django-defender/pull/82 the Redis URL can be picked up from Django's CACHES, so that makes it at least easier to configure - but using the CACHES in the first place might make the code and maintenance easier in general.

**Comment by kencochrane** [comment]
The Django Cache Framework (DCF) is too high level, it doesn't offer access to the lower level Redis features that we need in order to work. The cache framework was built for caching, and what we are doing isn't caching, it is more then that.
