### ISSUE TITLE
username_block_signal send multiple times

### ISSUE THREAD

**Issue by horida** [kencochrane/django-defender#135]
When blocking a user a signal is send in `defender/utils.py:block_username`
https://github.com/kencochrane/django-defender/blob/master/defender/utils.py#L197

However, this happens on every call of `defender/utils.py:record_failed_attemp` in
https://github.com/kencochrane/django-defender/blob/master/defender/utils.py#L218
even though the user was already blocked before.

For instance, I want to send an email informing the user (if present) that she was blocked and this results into an email for each blocked login.

Is this on purpose?

**Comment by kencochrane** [comment]
@horida good question, I would suspect that we only need it the first time, but I'm not sure if there is a use case where someone wants to know every time. 

@williamboman wrote that functionality, so let's ask them. @williamboman do you see any issue if we only send the blocking signal when it is blocked and not after every invalid login?

Maybe we need to have a different signal for invalid login that happens every time, and then only trigger the blocked username/ip when it is blocked.

Open to ideas/suggestions.

**Comment by williamboman** [comment]
Ah that does seem like a flaw. That signal should indeed only be dispatched when a user conceptually becomes blocked. I would not oppose changing this behavior, although I no longer use this library.

**Comment by horida** [comment]
Thanks both! I can create a PR these days.

I like that currently the signal is only sent once a user is actually blocked. I would not change this behavior.
On the other hand, we could check if the user is already blocked before blocking it. Then, afterwards the signal is only sent if the user was not blocked before. Though, I'd leave the set blocked in both cases to avoid race conditions.

Something like


    already_blocked = is_user_already_locked(username)
    key = get_username_blocked_cache_key(username)
    if config.COOLOFF_TIME:
        REDIS_SERVER.set(key, 'blocked', config.COOLOFF_TIME)
    else:
        REDIS_SERVER.set(key, 'blocked')
    if not already_blocked:
        send_username_block_signal(username)

**Comment by horida** [comment]
here you go: https://github.com/kencochrane/django-defender/pull/137

**Comment by kencochrane** [comment]
completed with #137 thanks @horida and @williamboman
