### ISSUE TITLE
remove ViewDecoratorMiddleware

### ISSUE THREAD

**Issue by kencochrane** [kencochrane/django-defender#23]
I don't think we need ``ViewDecoratorMiddleware``, by removing this, it keeps the code small, and makes it easier to maintain. if we are going to remove it, best to do it now.

@shin- @marcusmartins  what do you think?

**Comment by shin-** [comment]
I don't mind.

**Comment by marcusmartins** [comment]
Sounds good to me

**Comment by kencochrane** [comment]
done
