### ISSUE TITLE
Invalid fields when views a AccessAttempt instance on Django Admin

### ISSUE THREAD

**Issue by marcusmartins** [kencochrane/django-defender#26]
AccessAttemptAdmin() class references existing fields when viewing a AccessAttempt instance on the django admin interface.

```
django.core.exceptions.FieldErrordefender_accessattempt_change
Unknown field(s) (get_data, post_data) specified for AccessAttempt. Check fields/fieldsets/exclude attributes of class AccessAttemptAdmin.
```

https://github.com/kencochrane/django-defender/blob/master/defender/admin.py#L37

**Comment by kencochrane** [comment]
@marcusmartins Can we close this?
