### ISSUE TITLE
Package is not installable via pip

### ISSUE THREAD

**Issue by tclancy** [kencochrane/django-defender#31]
I can see django-defender with `pip search defender` but installation fails saying no package meets the requirements as [none are listed here](https://pypi.python.org/simple/django-defender/).

**Comment by kencochrane** [comment]
Sorry about that, there was an error during the upload of the original package. you should be able to see them available now. 0.1.1 is the latest. 

https://pypi.python.org/simple/django-defender/

**Comment by tclancy** [comment]
Perfect, thanks!

**Comment by tclancy** [comment]
The pip install does not include the subfolders. Think you want to add the following to `setup.py`:

```
package_data={
    "defender": ["templates/*.html", "migrations/*.py", "south_migrations/*.py", "exampleapp/*.*"],
},
```

**Comment by kencochrane** [comment]
@tclancy thanks, how does this look? https://github.com/kencochrane/django-defender/pull/33/files#diff-2eeaed663bd0d25b7e608891384b7298R40

**Comment by tclancy** [comment]
Looks right to me, thanks. Sorry, I should be providing these as pull requests but you're responding too quickly.
