### ISSUE TITLE
IP Restriction Bypass Issue

### ISSUE THREAD

**Issue by mmetince** [kencochrane/django-defender#32]
https://www.mehmetince.net/bypassing-django-defender-ip-based-trackban/

**Comment by kencochrane** [comment]
Thanks for letting me know. It looks like the same issue affects django-axes as well. 

https://github.com/django-pci/django-axes/blob/master/axes/decorators.py#L87-L129

Any suggestions on best way to fix?

**Comment by mmetince** [comment]
Your welcome @kencochrane . I think we are dealing with 2 different situation here. First one is using socket module for IP validation which is can done easily with regular expression. Second thing is trusting XFF data. 

I suggest you to use directly tcp source ip address rather than XFF or any other kind of Header variables because of any of them can easily spoof  by attacker. If you choose this solution, socket module will not be issue anymore :) Also please look at how Django handles this. I believe they are ignoring XFF string.

**Comment by kencochrane** [comment]
@mmetince do you feel this issue can be closed now with the release of 0.2?

**Comment by mmetince** [comment]
Yes I do. I'm closing it @kencochrane
