### ISSUE TITLE
Custom login view.

### ISSUE THREAD

**Issue by eltonplima** [kencochrane/django-defender#39]
How to make the defender work on a custom login view?

Thanks!

**Comment by kencochrane** [comment]
you could wrap your custom login in your ``urls.py`` like this.

```
from defender.decorators import watch_login

url(r'^login/$', watch_login(views.custom_login), {
        "template_name": "profiles/login.html",
        "authentication_form": forms.MyAuthenticationForm,
    }, name='login'),
```

You might be able to just add the decorator directly on the ``custom_login`` view, but haven't tested that yet.

```
from defender.decorators import watch_login

@watch_login()
def custom_login(request):
    """ my custom login view """
    # login stuff here

```

**Comment by eltonplima** [comment]
Works perfect!!!

Just an observation: the watch_login dont need the parenthesis.

Thanks!!!

**Comment by kencochrane** [comment]
@eltonplima cool, thanks, sorry for the typo, I wrote it from memory in the github issue, it wasn't an actual code snippet.  We should add this to the docs so others know about it as well.
