### ISSUE TITLE
Open invitation to move django-defender to the django-pci organization

### ISSUE THREAD

**Issue by aclark4life** [kencochrane/django-defender#45]
If you ever get tired of maintaining this or just want to join forces :smile: (Looks very nice!) https://github.com/django-pci

**Comment by kencochrane** [comment]
@aclark4life I'll let you know, thanks!

**Comment by jedie** [comment]
https://github.com/django-pci -> 404

**Comment by kencochrane** [comment]
Doesn't look like that org exists anymore. @aclark4life is there a new one, or was it disbanded?

**Comment by aclark4life** [comment]
The main attraction to the django-pci organization was django-axes, which has moved to https://github.com/jazzband, and after which I removed the django-pci organization.

**Comment by kencochrane** [comment]
@aclark4life ok, thanks for the update. I'll close this issue then.
