### ISSUE TITLE
Redis data needs to be decoded to string for Python 3

### ISSUE THREAD

**Issue by nephridium** [kencochrane/django-defender#46]
On Python 3.4 (Django 1.7) admin view /admin/defender/blocks throws TypeError "'str' does not support the buffer interface".

This is because with Python3 redis .keys() returns a bytes list while utils.strip_keys() expects a string list. I have a simple fix on my fork https://github.com/nephridium/django-defender/tree/decode_redis_data. If you like I can do a PR?

**Comment by kencochrane** [comment]
@nephridium if you could submit a PR, that would be great. Thank you.
