### ISSUE TITLE
Flex `install_requires` a bit

### ISSUE THREAD

**Issue by dmitry-mukhin** [kencochrane/django-defender#66]
Is there a reason to fix version requirements for `redis`, `hiredis`, `mockredispy`?
At least minor version changes should be allowed.

Currently this causes issues when using in apps that use newer version of dependencies (e.g. `redis==2.10.5`).

**Comment by kencochrane** [comment]
No, I don't think there is a reason other then we know those work, we should be able to pin it better so that the minor version are ok to use, and put a top limit on the more risky ones. Feel free to submit a PR to put it the way you want, and if it looks good, I'll merge right away.

**Comment by dmitry-mukhin** [comment]
great!

**Comment by dmitry-mukhin** [comment]
closed via #67
