### ISSUE TITLE
Delaying requests instead of blocking users

### ISSUE THREAD

**Issue by shnela** [kencochrane/django-defender#69]
Did you consider increasing request time instead of blocking user?

Increasing request time is a good way to protect from brutforce and doesn't block user account.

**Comment by kencochrane** [comment]
@shnela I haven't thought about that. How would that work? Would it cause any server resource issues?

**Comment by shnela** [comment]
@kencochrane 

Sorry, I overlook  DEFENDER_COOLOFF_TIME option... 
It does the right job.
