### ISSUE TITLE
Custom function for unloading username from request

### ISSUE THREAD

**Issue by shnela** [kencochrane/django-defender#70]
I've used `django-defender` in my application and it works well for standard login form, but it's not enough.
I have problem, because I'm also using `django-rest-framework`, so someone can still use rest api to to compromise passwords with brutforce attack.

I've tried to override `rest_framework.authentication.BasicAuthentication` class, but there's problem with some of `defender.utils` functions:

- `def is_already_locked(request):`
- `def check_request(request, login_unsuccessful):`
- `def add_login_attempt_to_db(request, login_valid):`

All these functions unloads _username_ like this:
`username = request.POST.get(config.USERNAME_FORM_FIELD, None)`

Unfortunately, getting username from `rest_framework's` requests isn't that simple and requires more complicated code.
I had no problems with other request parameters such as `user_agent` or `ip_address`.

Of course I can copy-paste some lines from `defender.utils`, but I think it's not the best idea.

I suggest to add to every function which uses request to unload _userid_ optional argument: `get_username_from_request`.

What do you think about that?

**Comment by kencochrane** [comment]
@shnela seems reasonable, would you be able to submit a PR?

**Comment by shnela** [comment]
Yes, I will do it tomorrow.
W dniu pt., 10.03.2017 o 18:33 Ken Cochrane <notifications@github.com>
napisał(a):

**Comment by kencochrane** [comment]
@shnela thank you
