### ISSUE TITLE
New PyPI release

### ISSUE THREAD

**Issue by HuntedCodes** [kencochrane/django-defender#73]
Greetings,

The [current PyPI package](https://pypi.python.org/pypi/django-defender) is version 0.4.2, which has a [`urls.py` file that breaks](https://github.com/kencochrane/django-defender/blob/v0.4.2/defender/urls.py) with current versions of Django.

```
  File "/home/debian/.virtualenvs/test/lib/python3.4/site-packages/defender/urls.py", line 1, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name 'patterns'
```

I see that this is already [fixed in the master branch](https://github.com/kencochrane/django-defender/blob/master/defender/urls.py). Any chance of updating the package on PyPI?

**Comment by kencochrane** [comment]
@HuntedCodes thanks for reminding me, I'll do it now.

**Comment by kencochrane** [comment]
@HuntedCodes https://pypi.python.org/pypi/django-defender/0.4.3

**Comment by HuntedCodes** [comment]
Thanks for the quick release.
