### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by msenol86** [kencochrane/django-defender#75]
> > To make it works add BasicAuthenticationDefender to DEFAULT_AUTHENTICATION_CLASSES in your settings.py.

BasicAuthenticationDefender should be above other auth methods in DEFAULT_AUTHENTICATION_CLASSES

**Comment by kencochrane** [comment]
@msenol86 thanks for the heads up, if you could submit a PR to make the doc fix, that would be awesome.
