### ISSUE TITLE
Blocks view fails if blocked usernames contain + sign

### ISSUE THREAD

**Issue by israel-tk** [kencochrane/django-defender#76]
I'm using a system where we use emails as usernames.

If an username like `user+test@domain.tld` gets blocked, then the rendering of `/admin/defender/blocks/` fails with the following error:

>  Reverse for 'defender_unblock_username_view' with arguments '(u'user+test@domain.tld',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'admin/defender/blocks/username/(?P<username>[A-Za-z0-9-._@]+)/unblock$']

Obviously that's because the `+` is not in the group of allowed chars for the regexp. Can we make the regexp a bit more permissive? I understand a `+` sign is OK in an URL and as part of a username.

**Comment by kencochrane** [comment]
That sounds fine, feel free to submit a PR and I'll review, and if it looks good, we can merge.

**Comment by dukebody** [comment]
Submitted a PR with my personal GH account. Comments appreciated! :)

**Comment by kencochrane** [comment]
@dukebody thank you. I have merged the PR, if it looks good to people, we can cut a new release.

**Comment by dukebody** [comment]
My pleasure. Thanks for the package and the quick turnaround! Perhaps we can cut a new release together with the Django 1.11 support.

**Comment by kencochrane** [comment]
Sounds like a plan.

**Comment by dukebody** [comment]
This issue is fixed in master and therefore can be closed.

**Comment by kencochrane** [comment]
Thanks, closing.
