### ISSUE TITLE
Taking redis client from django.core.cache

### ISSUE THREAD

**Issue by Franr** [kencochrane/django-defender#81]
Hello there. I have a little suggestion for the package. It is not so cool to re-declare your Redis url when you already have it on the settings. I have a quick workaround and would like your opinion.

First, add a new setting to the package: `DEFENDER_REDIS_NAME`. Is the name of the cache you will use, taken from the `CACHES` django setting.

Second, some code:

- defender/connection.py
```python
from django.core.cache import caches

def get_redis_connection():
    ...
    elif config.DEFENDER_REDIS_NAME:
        return caches[config.DEFENDER_REDIS_NAME].get_master_client()
    ...
```
Tried it and worked fine. If you are not against it, I can create a PR really quick.

**Comment by kencochrane** [comment]
@Franr I think that seems reasonable, I would probably change it a little, so that we check to make sure the caches dict has that key before we get the value. It is a little safer so it doesn't throw a `KeyError` if the name is wrong.

```
from django.core.cache import caches

def get_redis_connection():
    ...
    elif config.DEFENDER_REDIS_NAME and caches.has_key(config.DEFENDER_REDIS_NAME):
        return caches[config.DEFENDER_REDIS_NAME].get_master_client()
    ...
```

**Comment by Franr** [comment]
Good point. But in that case, the lib will try to use the `DEFENDER_REDIS_URL` setting, which will be null, and the default config will be used instead, leading to more confusion maybe? :stuck_out_tongue: 

I would prefer to make it explicitly fail, so you can quickly now where is the error and fix it in 2 seconds hehe. I will create a PR and we can discuss over it.
