### ISSUE TITLE
whitelist/blacklist

### ISSUE THREAD

**Issue by jasonbevan** [kencochrane/django-defender#83]
Thanks for the great App!
where can I edit whitelist/blacklist?

thanks

**Comment by kencochrane** [comment]
dedicated whitelist/blacklist isn't implemented yet: see https://github.com/kencochrane/django-defender/issues/50

**Comment by jasonbevan** [comment]
#50 sounds like a very useful feature, I hope it gets added in the future. 
Thanks!

**Comment by kencochrane** [comment]
@jasonbevan if you find it useful, we are looking for someone to add the feature, feel free to submit a PR.

**Comment by kencochrane** [comment]
closing since this is covered in #50
