### ISSUE TITLE
django admin

### ISSUE THREAD

**Issue by jasonbevan** [kencochrane/django-defender#84]
On django admin >> access attempt everyone gets 127.0.0.1 under ip address. Showldn't I see the user's IP? and also, how do I block an offender?

Thanks

**Comment by kencochrane** [comment]
If you are behind a reverse proxy you will need to set the `DEFENDER_REVERSE_PROXY_HEADER` and `DEFENDER_BEHIND_REVERSE_PROXY` settings so that it knows where to get the correct IP address.

**Comment by jasonbevan** [comment]
That worked! thanks.

**Comment by kencochrane** [comment]
Great, closing the issue.
