### ISSUE TITLE
defender for API

### ISSUE THREAD

**Issue by MattBlack85** [kencochrane/django-defender#85]
Hi, I'd like to use the package for protecting a login API url, the internals should be adjusted a bit (like checking against 401 instead of 302) but I think passing an argument to the decorator should make it possible. Also I'd really love to add the message on failed request to the db as a celery task.

@kencochrane thoughts? If you think it's ok I could work on making this happen

**Comment by kencochrane** [comment]
I think that is fine, we should make them two different PRs and we should make it so that celery isn't required for the second one. If they have celery installed or the setting is turned on, then use celery, if not do it the way we have it today. 

Thanks

**Comment by MattBlack85** [comment]
👍

**Comment by mehtamanan** [comment]
I want this so badly :(

**Comment by kencochrane** [comment]
@mehtamanan which part? https://github.com/kencochrane/django-defender/pull/86 gets it partially there.

**Comment by mehtamanan** [comment]
@kencochrane I want to add the functionality to a specific view/URL since I'm building a rest service! I send a post request w username and password attributes to an endpoint and I get a jwt back if the credentials match! I want to defend that endpoint ...

**Comment by mehtamanan** [comment]
Are you planning to release a new version with #86 anytime soon?

**Comment by kencochrane** [comment]
there are a few more things in the works, once they are done, we will make a new release.

**Comment by mehtamanan** [comment]
Looking forward to it!  Thanks :)

**Comment by MattBlack85** [comment]
Since the celery thing has its own task and the API goal has been achieved I'm closing this
