### ISSUE TITLE
Features??

### ISSUE THREAD

**Issue by jasonbevan** [kencochrane/django-defender#89]
How many of these features are actually available?

Log all login attempts to the database
support for reverse proxies with different headers for IP addresses
rate limit based on:
    username
    ip address
use redis for the blacklist
configuration
    redis server
        host
        port
        database
        password
        key_prefix
    block length
    number of incorrect attempts before block
95% code coverage
full documentation
Ability to store login attempts to the database
Management command to clean up login attempts database table
admin pages
    list of blocked usernames and ip's
    ability to unblock people
    list of recent login attempts
Can be easly adapted to custom authentication method.

**Comment by kencochrane** [comment]
Should be all, except for backlist, which is currently in design stage.

**Comment by kencochrane** [comment]
closing this since it isn't an issue. all features are listed in the readme, if you have an actual issue, please let us know
