### ISSUE TITLE
Few middleware problems? Django 1.11.2

### ISSUE THREAD

**Issue by Temeez** [kencochrane/django-defender#92]
middleware.py
```
                our_decorator = watch_login()
                watch_login_method = method_decorator(our_decorator)
```
Whats the point of this mess? Besides it throwing `TypeError: watch_login() takes exactly 1 argument (0 given)` can't it be just one line like it was before?

Like this: `watch_login_method = method_decorator(watch_login)`

Also for django-defender to work with the new django **MIDDLEWARE** I need to do the following to the middleware:
```
try:
    from django.utils.deprecation import MiddlewareMixin as MIDDLEWARE_BASE_CLASS
except ImportError:
    MIDDLEWARE_BASE_CLASS = object
```
Add this on top of the middleware.py and then swap the `class FailedLoginMiddleware(object):` to `class FailedLoginMiddleware(MIDDLEWARE_BASE_CLASS):`

Without doing these changes to the current middleware.py django runserver doesn't even "start". I am on django 1.11.2

Is the current 0.5 version actually running on someones django 1.11.x project? 😂

**Comment by MattBlack85** [comment]
I'm not using the middleware, just the decorator and I'm fine. For the middleware you're right, the one from the package is not working properly, but after your suggestion the project works. Note that the decorator has changed on 0.5.0 and is now possible to decorate functions other than the admin login, I'm not getting any TypeError on django 1.11.2. Those two lines have been split cause the method_decorator function wasn't performing the conversion well if watch_login() was passed straight. Had no time to investigate that further tho

**Comment by kencochrane** [comment]
@teemez Thanks for letting us know. Does this require a code fix, a documentation fix, both? If you have the time and are willing, feel free to submit a PR, that would be very helpful.

**Comment by Temeez** [comment]
@MattBlack85 would the following do the same thing as the current one in the 0.5.0?
```
                our_decorator = watch_login
                watch_login_method = method_decorator(our_decorator)
```

@kencochrane code fix only (I think?). I can submit a PR later today.

**Comment by MattBlack85** [comment]
@Teemez not sure, will check shortly. Decorator now expects some args (or defaults) so It should be called like ()

**Comment by MattBlack85** [comment]
@Temeez if not called () tests fail (at least on django 1.11.2), though it seems the oneliner works

**Comment by Temeez** [comment]
Odd, I don't get the `TypeError` from the `watch_login()` anymore and I have done no code changes.. magic!

I'll make a PR for the **MIDDLEWARE** thing so it won't throw `TypeError: object.__init__() takes no parameters` error.

**Comment by kencochrane** [comment]
@Temeez can we close this issue?
